apiVersion: batch/v1
kind: CronJob
metadata:
  name : analysisjob
  labels:
    binance: gatherdata
spec:
  schedule: "*/9 * * * *"
  #schedule: "* 5 */15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analysisjob
            image: karthikdhanusu/gatherdataimg:masteranalysis
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: binance-volume  
              mountPath: "/mnt/binance"
          volumes:
          - name: binance-volume
            persistentVolumeClaim:
              claimName: binance-pvc
          restartPolicy: Never
          imagePullSecrets:
          - name: kdhanusu
  
