apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binance-pvc-hs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Gi
  storageClassName: csi-cinder-high-speed
