apiVersion: v1
kind: PersistentVolume
metadata:
  name: binance-volume
  labels:
    type: highspeed
spec:
  storageClassName: csi-cinder-high-speed
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/binance"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binance-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 490Gi
  storageClassName: csi-cinder-high-speed
