apiVersion: apps/v1
kind: Deployment
metadata:
  name: jump
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: jump
        image: karthikdhanusu/gatherdataimg:v1.2
        imagePullPolicy: Always
        command: ['sh', '-c', 'sleep 99999999999']
        volumeMounts:
        - name: binancevol
          mountPath: "/mnt/binance"
      volumes:
      - name: binancevol
        persistentVolumeClaim:
          claimName: nfs-pvc
      restartPolicy: Always
      imagePullSecrets:
      - name: kdhanusu

