apiVersion: batch/v1
kind: CronJob
metadata:
  name : gatherdatajob
  labels:
    binance: gatherdata
spec:
  #schedule: "*/1 * * * *"
  schedule: "* 5 */15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gatherdatajob
            image: karthikdhanusu/gatherdataimg:v1.2
            command: ["sh","-c","sleep 12000 && python3.8", "./gatherdat.py"]
            imagePullPolicy: Always
            volumeMounts:
            - name: binancevol
              mountPath: "/mnt/binance"
          volumes:
          - name: binancevol
            persistentVolumeClaim:
              claimName: binance-pvc-hs
          restartPolicy: Never
          automountServiceAccountToken: false
          imagePullSecrets:
          - name: kdhanusu
            #initContainers:
            #- name: init-pvfoldercreate
            #image: busybox:1.28
            #command: ['sh', '-c', 'mkdir -f /mnt/binance/gatherdata/']
            #volumeMounts:
            #- name: binancevol
            #  mountPath: "/mnt/binance"
            #volumes:
            #- name: binancevol
            #  persistentVolumeClaim:
            #    claimName: binance-pvc-hs     
                    

