kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  volumeName: "pvc-c273a7e3-d8fb-42e0-822f-fd1436513464"
  resources:
    requests:
      storage: 2500Gi
