apiVersion: batch/v1
kind: CronJob
metadata:
  name : njitparalleljob-1
  labels:
    binance: njit
spec:
  #schedule: "*/1 * * * *"
  schedule: "1 7 */15 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: njit-1
            image: karthikdhanusu/gatherdataimg:v1.2
            command: ["python3.8", "./njitparatrue_vpt.py"]
            imagePullPolicy: Always
            volumeMounts:
            - name: binancevol
              mountPath: "/mnt/binance"
          volumes:
          - name: binancevol
            persistentVolumeClaim:
              claimName: nfs-pvc
          restartPolicy: Never
          automountServiceAccountToken: false
          imagePullSecrets:
          - name: kdhanusu
          
